spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  datasource:
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:XE
    #    url: jdbc:oracle:thin:@localhost:1521/xe
    #    url: jdbc:mariadb://localhost:3306/bootex
    username: bellowschool
    password: bellowschool
    #    driver-class-name: oracle.jdbc.OracleDriver
    #    driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2

mybatis:
  type-aliases-package: com.bellowschool.vo
  mapper-locations: sqlmap/**/*.xml

logging:
  level:
    jdbc:
      sqlonly: info
      sqltiming: warn
      audit: debug
      resultset: false
      resultsettable: trace
    org.springframework.web: info
    com.zaxxer.hikari.HikariDataSource: error

server:
  error:
    include-exception: false
    include-stacktrace: never
    path:
    whitelabel:
      enabled: true
  port: 8080